CREATE TABLE "USER" (
  "USER_EMAIL" VARCHAR2(30 CHAR) CONSTRAINT "PK_USER" PRIMARY KEY,
  "USER_PASSWORD" VARCHAR2(10 CHAR),
  "USER_NAME" VARCHAR2(30 CHAR),
  "USER_BALANCE" NUMBER(10),
  "ROLE" VARCHAR2(1000 CHAR) NOT NULL
);

CREATE INDEX "IDX_USER__ROLE" ON "USER" ("ROLE");

ALTER TABLE "USER" ADD CONSTRAINT "FK_USER__ROLE" FOREIGN KEY ("ROLE") REFERENCES "ROLE" ("ROLE_NAME");
CREATE TABLE "ROLE" (
  "ROLE_NAME" VARCHAR2(1000 CHAR) CONSTRAINT "PK_ROLE" PRIMARY KEY,
  "ROLE_DESCRIPTION" VARCHAR2(30 CHAR)
);

CREATE SEQUENCE "ROLE_SEQ" NOCACHE;

CREATE TRIGGER "ROLE_BI"
  BEFORE INSERT ON "ROLE"
  FOR EACH ROW
BEGIN
  IF :NEW."ROLE_NAME" IS NULL THEN
    SELECT "ROLE_SEQ".NEXTVAL INTO :NEW."ROLE_NAME" FROM DUAL;
  END IF;
END;;

CREATE SEQUENCE "USER_SEQ" NOCACHE;

CREATE TRIGGER "USER_BI"
  BEFORE INSERT ON "USER"
  FOR EACH ROW
BEGIN
  IF :NEW."USER_EMAIL" IS NULL THEN
    SELECT "USER_SEQ".NEXTVAL INTO :NEW."USER_EMAIL" FROM DUAL;
  END IF;
END;;

CREATE TABLE "CART" (
  "CART_ID" NUMBER(10) CONSTRAINT "PK_CART" PRIMARY KEY,
  "USER" VARCHAR2(30 CHAR) NOT NULL
);

CREATE INDEX "IDX_CART__USER" ON "CART" ("USER");

ALTER TABLE "CART" ADD CONSTRAINT "FK_CART__USER" FOREIGN KEY ("USER") REFERENCES "USER" ("USER_EMAIL");

CREATE SEQUENCE "CART_SEQ" NOCACHE;

CREATE TRIGGER "CART_BI"
  BEFORE INSERT ON "CART"
  FOR EACH ROW
BEGIN
  IF :NEW."CART_ID" IS NULL THEN
    SELECT "CART_SEQ".NEXTVAL INTO :NEW."CART_ID" FROM DUAL;
  END IF;
END;;

CREATE TABLE "ORDER" (
  "ORDER_DATE" TIMESTAMP CONSTRAINT "PK_ORDER" PRIMARY KEY,
  "ORDER_PRICE" NUMBER(10),
  "CART" NUMBER(10) NOT NULL
);

CREATE INDEX "IDX_ORDER__CART" ON "ORDER" ("CART");

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_ORDER__CART" FOREIGN KEY ("CART") REFERENCES "CART" ("CART_ID");

CREATE SEQUENCE "ORDER_SEQ" NOCACHE;

CREATE TRIGGER "ORDER_BI"
  BEFORE INSERT ON "ORDER"
  FOR EACH ROW
BEGIN
  IF :NEW."ORDER_DATE" IS NULL THEN
    SELECT "ORDER_SEQ".NEXTVAL INTO :NEW."ORDER_DATE" FROM DUAL;
  END IF;
END;;

CREATE TABLE "PRODUCT" (
  "PRODUCT_NAME" VARCHAR2(1000 CHAR) CONSTRAINT "PK_PRODUCT" PRIMARY KEY,
  "PRODUCT_PRICE" NUMBER(10),
  "PRODUCT_TYPE" VARCHAR2(1000 CHAR),
  "PRODUCT_BRAND" VARCHAR2(1000 CHAR),
  "PRODUCT_DESCRIPTION" VARCHAR2(1000 CHAR),
  "PRODUCT_PHOTO" NUMBER,
  "ID" NUMBER(10)
);

CREATE INDEX "IDX_PRODUCT__ID" ON "PRODUCT" ("ID");

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT__ID" FOREIGN KEY ("ID") REFERENCES "CART" ("CART_ID");

CREATE SEQUENCE "PRODUCT_SEQ" NOCACHE;

CREATE TRIGGER "PRODUCT_BI"
  BEFORE INSERT ON "PRODUCT"
  FOR EACH ROW
BEGIN
  IF :NEW."PRODUCT_NAME" IS NULL THEN
    SELECT "PRODUCT_SEQ".NEXTVAL INTO :NEW."PRODUCT_NAME" FROM DUAL;
  END IF;
END;